# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/hafizadeel7266@gmail.com/NEXUS_DATAPLATFORM-WPP-UNIFIED/NEXUS_DATAPLATFORM-PIPELINE")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM nexus_dataplatform-wpp.default.sample_aggregation_nexus_dataplatform_pipeline"))
